export interface StationData {
  stationId: number;
  city: string;
  state: string;
}

export const malaysia_station: StationData[] = [
    { stationId: 9491, state: "Melaka", city: "Alor Gajah" },
    { stationId: 2581, state: "Kedah", city: "Alor Setar" },
    { stationId: 9490, state: "Penang", city: "Balik Pulau" },
    { stationId: 2591, state: "Pahang", city: "Balok Baru Kuantan" },
    { stationId: 2586, state: "Melaka", city: "Bandaraya Melaka" },
    { stationId: 2617, state: "Selangor", city: "Banting" },
    { stationId: 2625, state: "Kuala Lumpur", city: "Batu Muda" },
    { stationId: 9493, state: "Johor", city: "Batu Pahat" },
    { stationId: 9498, state: "Terengganu", city: "Besut" },
    { stationId: 2607, state: "Sarawak", city: "Bintulu" },
    { stationId: 2587, state: "Melaka", city: "Bukit Rambai" },
    { stationId: 2626, state: "Kuala Lumpur", city: "Cheras" },
    { stationId: 2592, state: "Pahang", city: "Indera Mahkota Kuantan" },
    { stationId: 2593, state: "Pahang", city: "Jerantut" },
    { stationId: 2599, state: "Perlis", city: "Kangar" },
    { stationId: 2622, state: "Terengganu", city: "Kemaman" },
    { stationId: 2603, state: "Sabah", city: "Keningau" },
    { stationId: 9499, state: "Sabah", city: "Kimanis" },
    { stationId: 2619, state: "Selangor", city: "Klang" },
    { stationId: 9494, state: "Johor", city: "Kluang" },
    { stationId: 9556, state: "Kelantan", city: "Kota Bharu" },
    { stationId: 2604, state: "Sabah", city: "Kota Kinabalu" },
    { stationId: 2577, state: "Johor", city: "Kota Tinggi" },
    { stationId: 2618, state: "Selangor", city: "Kuala Selangor" },
    { stationId: 2623, state: "Terengganu", city: "Kuala Terengganu" },
    { stationId: 2610, state: "Sarawak", city: "Kuching" },
    { stationId: 9488, state: "Kedah", city: "Kulim" },
    { stationId: 2627, state: "Wilayah Persekutuan", city: "Labuan" },
    { stationId: 2583, state: "Kedah", city: "Langkawi" },
    { stationId: 2578, state: "Johor", city: "Larkin" },
    { stationId: 2611, state: "Sarawak", city: "Limbang" },
    { stationId: 9489, state: "Penang", city: "Minden" },
    { stationId: 2612, state: "Sarawak", city: "Miri" },
    { stationId: 9501, state: "Sarawak", city: "Mukah" },
    { stationId: 2588, state: "Negeri Sembilan", city: "Nilai" },
    { stationId: 2624, state: "Terengganu", city: "Paka" },
    { stationId: 2580, state: "Johor", city: "Pasir Gudang" },
    { stationId: 2596, state: "Perak", city: "Pegoh Ipoh" },
    { stationId: 9495, state: "Johor", city: "Pengerang" },
    { stationId: 2620, state: "Selangor", city: "Petaling Jaya" },
    { stationId: 2589, state: "Negeri Sembilan", city: "Port Dickson" },
    { stationId: 10485, state: "Wilayah Persekutuan", city: "Putrajaya" },
    { stationId: 9496, state: "Pahang", city: "Rompin" },
    { stationId: 9500, state: "Sarawak", city: "Samalaju" },
    { stationId: 2613, state: "Sarawak", city: "Samarahan" },
    { stationId: 2605, state: "Sabah", city: "Sandakan" },
    { stationId: 2614, state: "Sarawak", city: "Sarikei" },
    { stationId: 2601, state: "Penang", city: "Seberang Jaya" },
    { stationId: 2600, state: "Penang", city: "Seberang Perai" },
    { stationId: 9492, state: "Johor", city: "Segamat" },
    { stationId: 2590, state: "Negeri Sembilan", city: "Seremban" },
    { stationId: 2597, state: "Perak", city: "Seri Manjung" },
    { stationId: 2621, state: "Selangor", city: "Shah Alam" },
    { stationId: 2615, state: "Sarawak", city: "Sibu" },
    { stationId: 2616, state: "Sarawak", city: "Sri Aman" },
    { stationId: 2582, state: "Kedah", city: "Sungai Petani" },
    { stationId: 2595, state: "Perak", city: "Taiping" },
    { stationId: 2585, state: "Kelantan", city: "Tanah Merah" },
    { stationId: 10484, state: "Johor", city: "Tangkak" },
    { stationId: 2598, state: "Perak", city: "Tanjung Malim" },
    { stationId: 2594, state: "Perak", city: "Tasek Ipoh" },
    { stationId: 2606, state: "Sabah", city: "Tawau" },
    { stationId: 9497, state: "Pahang", city: "Temerloh" }
]